client_config:
  type: continuous
  size: 1-100
  times_or_steps: 1
---
client_config:
  type: continuous
  size: 100-1000
  times_or_steps: 10
---
client_config:
  type: continuous
  size: 1000-10000
  times_or_steps: 100
---
client_config: 
  type: discrete 
  size: [1kb, 10kb, 100kb, 1mb, 10mb]
  times_or_steps: 10
